name: elearning
description: A new Flutter project.

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_calendar_carousel: ^2.4.3
  http:
  dio: ^5.3.3
  gap: ^3.0.1
  flutter_pdfview: ^1.3.2
  open_file: ^3.3.2
  permission_handler: ^11.0.1
  video_player: ^2.7.2
  chewie: ^1.7.1
  shimmer: ^3.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  connectivity_plus: ^6.0.3
  sqflite: ^2.3.0
  path: ^1.8.3
  sembast: ^3.5.0+1
  sembast_sqflite: ^2.2.0
  flutter_screenutil: ^5.7.0
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.0.2
  flutter_swipe_button: ^2.1.1+1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  path_provider: ^2.1.3
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  get: ^4.6.5
  fluttertoast: ^8.2.6
  responsive_framework: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Red Hat Display
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/RedHatDisplay-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
          style: italic
          weight: 600
    - family: BoxIcons
      fonts:
        - asset: assets/fonts/BoxIcons.ttf
